-- CREATION OF VIEWS FOR EVERY SPECIFIC GROUP
-- CATEGORIZING AS 'A','B','C','D'

CREATE VIEW `GROUP_A` AS
    SELECT * FROM GROUP_LEAUGE
    WHERE GROUPID = 'A'; 

CREATE VIEW `GROUP_B` AS
    SELECT * FROM GROUP_LEAUGE
    WHERE GROUPID = 'B'; 

CREATE VIEW `GROUP_C` AS
    SELECT * FROM GROUP_LEAUGE
    WHERE GROUPID = 'C'; 

CREATE VIEW `GROUP_D` AS
    SELECT * FROM GROUP_LEAUGE
    WHERE GROUPID = 'D'; 

