DESC TEAMS;

-- -- DIABLE SAFE UPDATE MODE 
SET SQL_SAFE_UPDATES=0;

INSERT INTO TEAMS ( TEAM_ID,TEAM_NAME,CAPTAIN,VICE_CAPTAIN)
VALUES  ('AFG','AFGHANISTAN','RASHID KHAN','IBRAHIM ZADRAN'),
		('AUS','AUSTRALIA','MITCHELL MARSH','MATTHEW WADE'),
        ('BAN','BANGLADESH','NAJMUL HOSSAIN SHANTO','TASKIN AHMED'),
        ('CAN','CANADA','SAAD BIN ZAFAR',NULL),
        ('ENG','ENGLAND','JOS BUTTLER','MOEEN ALI'),
        ('IND','INDIA','ROHIT SHARMA','HARDIK PANDYA'),
        ('IRE','IRELAND','PAUL STIRLING',null),
        ('NAM','NAMIBIA','GERHARD ERASMUS','JJ SMIT'),
		('NEP','NEPAL','ROHIT PAUDEL','ROHIT PAUDEL'),
        ('NED','NETHERLANDS','SCOTT EDWARDS',NULL),
        ('NZ','NEW ZEALAND','KANE WILLIAMSON','MITCHELL SANTNER'),
        ('OMA','OMAN','AQIB ILYAS',NULL),
        ('PNG','PAPUA NEW GUINEA','ASSADOLLAH VALA',NULL),
        ('PAK','PAKISTAN','BABAR AZAM',NULL),
        ('SCOT','SCOTLAND','RICHIIE BERRINGTON','MATTHEW CROSS'),
        ('SA','SOUTH AFRICA','AIDEN MARKRAM',NULL),
        ('SL','SRI LANKA','WANINDU HARASARNGA','CHARITH ASALANKA'),
        ('UGA','UGANDA','BRIAN MASABA','RIAZAT ALI SHAH'),
        ('US','UNITED STATES','MONANK PATEL','AARON JONES'),
        ('WI','WEST INDIES','ROVMAN POWELL','SHAI HOPE');
        
SELECT count(*) FROM TEAMS;

